-- MCEO Sales OS v4｜Supabase database setup
-- Run this once in Supabase Dashboard > SQL Editor.

create table if not exists public.student_workspaces (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_key text not null default 'sales-os-v1',
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, workspace_key)
);

create index if not exists student_workspaces_user_id_idx
  on public.student_workspaces (user_id);

alter table public.student_workspaces enable row level security;

drop policy if exists "Students can read own workspace" on public.student_workspaces;
create policy "Students can read own workspace"
  on public.student_workspaces for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Students can create own workspace" on public.student_workspaces;
create policy "Students can create own workspace"
  on public.student_workspaces for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Students can update own workspace" on public.student_workspaces;
create policy "Students can update own workspace"
  on public.student_workspaces for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Students can delete own workspace" on public.student_workspaces;
create policy "Students can delete own workspace"
  on public.student_workspaces for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- AI usage is server-only. RLS is enabled with no client policies.
create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  engine text not null check (engine in ('atass', 'closer_disc', 'objection_disc')),
  status text not null default 'started' check (status in ('started', 'succeeded', 'failed')),
  output_chars integer,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_user_created_idx
  on public.ai_usage (user_id, created_at desc);

alter table public.ai_usage enable row level security;

revoke all on public.ai_usage from anon, authenticated;
grant select, insert, update, delete on public.ai_usage to service_role;
grant usage, select on sequence public.ai_usage_id_seq to service_role;
